#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

# 600K phase-2 wrapper (all 4 web datasets).
# This delegates to the existing all4 script with higher defaults suitable
# for larger targets.
RUN_TAG="${RUN_TAG:-all4_t600k}"
TARGET_TOTAL="${TARGET_TOTAL:-600000}"
POST_TARGET_TOTAL="${POST_TARGET_TOTAL:-600000}"

AUTO_RAMP="${AUTO_RAMP:-1}"
RAMP_MAX_ROUNDS="${RAMP_MAX_ROUNDS:-8}"
RAMP_FACTOR="${RAMP_FACTOR:-2}"

MAX_DOCUMENTS_PER_DATASET="${MAX_DOCUMENTS_PER_DATASET:-1000000}"

STACKEXCHANGE_MAX_POSTS_PER_SITE="${STACKEXCHANGE_MAX_POSTS_PER_SITE:-80000}"
STACKEXCHANGE_MAX_POSTS_PER_SITE_MAX="${STACKEXCHANGE_MAX_POSTS_PER_SITE_MAX:-1200000}"
STACKEXCHANGE_MAX_COMMENTS_PER_SITE="${STACKEXCHANGE_MAX_COMMENTS_PER_SITE:-40000}"

GUTENBERG_MAX_DOCS="${GUTENBERG_MAX_DOCS:-400000}"
GUTENBERG_MAX_DOCS_MAX="${GUTENBERG_MAX_DOCS_MAX:-2400000}"

WIKISOURCE_MAX_DOCS_PER_WIKI="${WIKISOURCE_MAX_DOCS_PER_WIKI:-50000}"
WIKISOURCE_MAX_DOCS_PER_WIKI_MAX="${WIKISOURCE_MAX_DOCS_PER_WIKI_MAX:-300000}"
WIKISOURCE_MAX_TOTAL_DOCS="${WIKISOURCE_MAX_TOTAL_DOCS:-500000}"
WIKISOURCE_MAX_TOTAL_DOCS_MAX="${WIKISOURCE_MAX_TOTAL_DOCS_MAX:-3000000}"

YTCOMMENTS_MAX_DOCS="${YTCOMMENTS_MAX_DOCS:-500000}"
YTCOMMENTS_MAX_DOCS_MAX="${YTCOMMENTS_MAX_DOCS_MAX:-3000000}"
YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG="${YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG:-80}"
YTCOMMENTS_MAX_COMMENTS_PER_VIDEO="${YTCOMMENTS_MAX_COMMENTS_PER_VIDEO:-300}"
YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO="${YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO:-10}"

RUN_TAG="$RUN_TAG" \
TARGET_TOTAL="$TARGET_TOTAL" \
POST_TARGET_TOTAL="$POST_TARGET_TOTAL" \
AUTO_RAMP="$AUTO_RAMP" \
RAMP_MAX_ROUNDS="$RAMP_MAX_ROUNDS" \
RAMP_FACTOR="$RAMP_FACTOR" \
MAX_DOCUMENTS_PER_DATASET="$MAX_DOCUMENTS_PER_DATASET" \
STACKEXCHANGE_MAX_POSTS_PER_SITE="$STACKEXCHANGE_MAX_POSTS_PER_SITE" \
STACKEXCHANGE_MAX_POSTS_PER_SITE_MAX="$STACKEXCHANGE_MAX_POSTS_PER_SITE_MAX" \
STACKEXCHANGE_MAX_COMMENTS_PER_SITE="$STACKEXCHANGE_MAX_COMMENTS_PER_SITE" \
GUTENBERG_MAX_DOCS="$GUTENBERG_MAX_DOCS" \
GUTENBERG_MAX_DOCS_MAX="$GUTENBERG_MAX_DOCS_MAX" \
WIKISOURCE_MAX_DOCS_PER_WIKI="$WIKISOURCE_MAX_DOCS_PER_WIKI" \
WIKISOURCE_MAX_DOCS_PER_WIKI_MAX="$WIKISOURCE_MAX_DOCS_PER_WIKI_MAX" \
WIKISOURCE_MAX_TOTAL_DOCS="$WIKISOURCE_MAX_TOTAL_DOCS" \
WIKISOURCE_MAX_TOTAL_DOCS_MAX="$WIKISOURCE_MAX_TOTAL_DOCS_MAX" \
YTCOMMENTS_MAX_DOCS="$YTCOMMENTS_MAX_DOCS" \
YTCOMMENTS_MAX_DOCS_MAX="$YTCOMMENTS_MAX_DOCS_MAX" \
YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG="$YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG" \
YTCOMMENTS_MAX_COMMENTS_PER_VIDEO="$YTCOMMENTS_MAX_COMMENTS_PER_VIDEO" \
YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO="$YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO" \
bash processing/second_phase_web_crawling/scripts/run_webcrawl_60k_all4.sh
