#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
export ROOT_DIR
export PYTHONPATH="${ROOT_DIR}"

export RUN_TAG="${RUN_TAG:-all4_sanity}"
export PIPELINE_STAGES="${PIPELINE_STAGES:-crawl construct}"
export AUTO_RAMP="${AUTO_RAMP:-0}"
export TARGET_TOTAL="${TARGET_TOTAL:-10000}"
export POST_TARGET_TOTAL="${POST_TARGET_TOTAL:-$TARGET_TOTAL}"
export SANITY_CHECK="${SANITY_CHECK:-1}"
export SANITY_LIMIT="${SANITY_LIMIT:-1000}"
export MAX_DOCUMENTS_PER_DATASET="${MAX_DOCUMENTS_PER_DATASET:-5000}"
export SHUFFLE_BUFFER_SIZE="${SHUFFLE_BUFFER_SIZE:-2000}"

# Keep crawl caps small if PIPELINE_STAGES is overridden to include crawl.
export STACKEXCHANGE_MAX_POSTS_PER_SITE="${STACKEXCHANGE_MAX_POSTS_PER_SITE:-2000}"
export STACKEXCHANGE_MAX_COMMENTS_PER_SITE="${STACKEXCHANGE_MAX_COMMENTS_PER_SITE:-500}"
export GUTENBERG_MAX_DOCS="${GUTENBERG_MAX_DOCS:-5000}"
export WIKISOURCE_MAX_DOCS_PER_WIKI="${WIKISOURCE_MAX_DOCS_PER_WIKI:-1000}"
export WIKISOURCE_MAX_TOTAL_DOCS="${WIKISOURCE_MAX_TOTAL_DOCS:-5000}"
export YTCOMMENTS_MAX_DOCS="${YTCOMMENTS_MAX_DOCS:-5000}"
export YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG="${YTCOMMENTS_MAX_VIDEO_PAGES_PER_LANG:-5}"
export YTCOMMENTS_MAX_COMMENTS_PER_VIDEO="${YTCOMMENTS_MAX_COMMENTS_PER_VIDEO:-50}"
export YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO="${YTCOMMENTS_MAX_COMMENT_PAGES_PER_VIDEO:-2}"

if [[ -z "${YOUTUBE_API_KEY:-}" ]]; then
  export SKIP_YTCOMMENTS="${SKIP_YTCOMMENTS:-1}"
fi

bash "$ROOT_DIR/processing/second_phase_web_crawling/scripts/run_webcrawl_300k_cap10M_all4.sh"
