#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# 600K phase-1 wrapper.
# Keep allow-other-languages OFF by default so sampling stays aligned with
# repo target language/genre/length distributions.
RUN_TAG="${RUN_TAG:-phase1_t600k}"
TOTAL_DOCS="${TOTAL_DOCS:-600000}"
POST_TARGET_TOTAL="${POST_TARGET_TOTAL:-600000}"
ALLOW_OTHER_LANGUAGES="${ALLOW_OTHER_LANGUAGES:-0}"

MAX_DOCUMENTS_PER_DATASET="${MAX_DOCUMENTS_PER_DATASET:-10000000}"
SHUFFLE_BUFFER_SIZE="${SHUFFLE_BUFFER_SIZE:-10000}"
CHUNK_PROBABILITY="${CHUNK_PROBABILITY:-0.7}"
TRUNCATE_TO_TOKENS="${TRUNCATE_TO_TOKENS:-2000}"
SEED="${SEED:-42}"

RUN_TAG="$RUN_TAG" \
TOTAL_DOCS="$TOTAL_DOCS" \
POST_TARGET_TOTAL="$POST_TARGET_TOTAL" \
ALLOW_OTHER_LANGUAGES="$ALLOW_OTHER_LANGUAGES" \
MAX_DOCUMENTS_PER_DATASET="$MAX_DOCUMENTS_PER_DATASET" \
SHUFFLE_BUFFER_SIZE="$SHUFFLE_BUFFER_SIZE" \
CHUNK_PROBABILITY="$CHUNK_PROBABILITY" \
TRUNCATE_TO_TOKENS="$TRUNCATE_TO_TOKENS" \
SEED="$SEED" \
bash processing/scripts/run_phase1_construction.sh
